# Generated by Django 5.1 on 2024-08-28 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destination_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('hotel', 'Hotel'), ('hostel', 'Hostel'), ('apartment', 'Apartment'), ('bnb', 'Bed and Breakfast'), ('camping', 'Camping'), ('other', 'Other')], max_length=50)),
                ('address', models.CharField(max_length=255)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
                ('estimated_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='utils/img/accommodations/')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodations', to='destination_app.destination')),
            ],
        ),
    ]
