# Generated by Django 5.1 on 2024-08-27 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destination_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('duration', models.IntegerField(choices=[(1, '1 Day'), (2, '2 Days'), (3, '3 Days')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='destination_app.destination')),
            ],
            options={
                'unique_together': {('destination', 'duration')},
            },
        ),
    ]
