# Generated by Django 5.1 on 2024-08-28 11:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accommodation_app', '0001_initial'),
        ('activity_app', '0001_initial'),
        ('destination_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Itinerary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('duration', models.IntegerField(choices=[(1, '1 Day'), (2, '2 Days'), (3, '3 Days')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itineraries', to='destination_app.destination')),
            ],
            options={
                'unique_together': {('destination', 'duration')},
            },
        ),
        migrations.CreateModel(
            name='ItineraryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(1, 'Day 1'), (2, 'Day 2'), (3, 'Day 3')])),
                ('description', models.TextField(blank=True, null=True)),
                ('accommodation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itinerary_details', to='accommodation_app.accommodation')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itinerary_details', to='activity_app.activity')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='itinerary_app.itinerary')),
            ],
            options={
                'verbose_name': 'Itinerary Detail',
                'verbose_name_plural': 'Itinerary Details',
                'ordering': ['itinerary', 'day'],
            },
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='itinerary_app.itinerary')),
            ],
            options={
                'unique_together': {('user', 'itinerary')},
            },
        ),
    ]
