# Generated by Django 5.1 on 2024-08-27 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation_app', '0001_initial'),
        ('activity_app', '0001_initial'),
        ('itinerary_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItineraryDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(1, 'Day 1'), (2, 'Day 2'), (3, 'Day 3')])),
                ('accommodation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itinerary_details', to='accommodation_app.accommodation')),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itinerary_details', to='activity_app.activity')),
                ('itinerary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='itinerary_app.itinerary')),
            ],
            options={
                'verbose_name': 'Itinerary Detail',
                'verbose_name_plural': 'Itinerary Details',
                'ordering': ['itinerary', 'day'],
            },
        ),
    ]
