# Generated by Django 5.1 on 2024-08-27 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itinerary_app', '0003_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='itinerarydetails',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
