# Generated by Django 5.1 on 2024-08-28 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('destination_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('adventure', 'Adventure'), ('cultural', 'Cultural'), ('nature', 'Nature'), ('gastronomic', 'Gastronomic'), ('historical', 'Historical'), ('relaxation', 'Relaxation')], max_length=50)),
                ('description', models.TextField()),
                ('estimated_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='utils/img/activities/')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='destination_app.destination')),
            ],
        ),
    ]
